# Generated by Django 4.0.4 on 2022-04-11 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Gry', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Produkty',
            new_name='Gry',
        ),
    ]
