# Generated by Django 4.0.4 on 2022-04-11 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gry', '0002_rename_produkty_gry'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=40)),
                ('opis', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Producent',
                'verbose_name_plural': 'Producenci',
            },
        ),
        migrations.AlterModelOptions(
            name='gry',
            options={'verbose_name': 'Gra', 'verbose_name_plural': 'Gry'},
        ),
    ]
