# Generated by Django 4.0.4 on 2022-04-11 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Gry', '0003_producent_alter_gry_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='gry',
            name='producent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Gry.producent'),
        ),
    ]
